// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeo-4kQXVkl_Q5l7mwHLlnZ_ozm9qnNn4',
    appId: '1:845011601757:web:b62ca34c7cf27b838f40b4',
    messagingSenderId: '845011601757',
    projectId: 'todo-app-6cd9b',
    authDomain: 'todo-app-6cd9b.firebaseapp.com',
    databaseURL: 'https://todo-app-6cd9b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todo-app-6cd9b.appspot.com',
    measurementId: 'G-Q8H398TWHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvP39olLi_3O2mvinqvk8isFXd43BqOvI',
    appId: '1:845011601757:android:7da122bdb5e76fb98f40b4',
    messagingSenderId: '845011601757',
    projectId: 'todo-app-6cd9b',
    databaseURL: 'https://todo-app-6cd9b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todo-app-6cd9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFyhYLrfxT3xVdEtJr26cUApVRbf75860',
    appId: '1:845011601757:ios:ea0bbf762159db8a8f40b4',
    messagingSenderId: '845011601757',
    projectId: 'todo-app-6cd9b',
    databaseURL: 'https://todo-app-6cd9b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todo-app-6cd9b.appspot.com',
    iosClientId: '845011601757-l1rnfbfrin9b2ipksidrtt25ms0ng1n8.apps.googleusercontent.com',
    iosBundleId: 'com.example.contactsApp',
  );
}
